sudo: required
dist: trusty

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; export CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.5"; export CC="clang-3.5"; fi
  
  # Info about Compiler
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  - python3 --version

  # Info about OS
  - uname -a
  - echo $TRAVIS_OS_NAME
  
  # Homebrew (Mac OSX)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated cmake || brew upgrade cmake; fi
  
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install netcdf; fi
  
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/bin:$PATH; fi
  
# APT (Linux)
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.8
      - george-edison55/cmake-3.x
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.8
      - cmake
      - libssl-dev
      - python3-nose
os:
  - linux
  - osx
  
env:
  - CONFIG=Release
  - CONFIG=Debug

language: cpp

compiler:
  - clang
  - gcc
  
matrix:
  exclude:
    # OSX boost is compiled with Clang (skip gcc builds)
    - os: osx
      compiler: gcc
      env: CONFIG=Release
      
    - os: osx
      compiler: gcc
      env: CONFIG=Debug

before_script:
  - mkdir build
  - pushd $(pwd)
  - cd build

  # Build on Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake ../; fi
  
  # Build on OSX 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake ../; fi
  
  # Build & Install
  - make
  
  - popd

script:
  - pushd $(pwd)
  - cd build

  # Run C/C++/Python unittests
  - ctest --output-on-failure --force-new-ctest-process

  - popd
 
notifications:
  email:
    recipients:
      - thfabian@student.ethz.ch
    on_success: never
    on_failure: always

