sudo: required
dist: trusty

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; export CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.8"; export CC="clang-3.8"; fi
  
  # Info about Compiler
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  
  # Info about OS
  - uname -a
  - echo $TRAVIS_OS_NAME
  
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="$TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  # Homebrew (Mac OSX)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python3; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip3 install numpy matplotlib nose; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install netcdf; fi
  
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/bin:${PATH}; fi
  
  # Install a recent CMake (unless already installed on OS X)
  - |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:$PATH
  else 
    if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
  fi
  
# APT (Linux)
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.8
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.8
      - libboost-all-dev
      - libssl-dev
      - python3-dev
      - python3-nose
      - python3-numpy
      - python3-matplotlib

os:
  - linux
  - osx
  
env:
  - CONFIG=Release
  - CONFIG=Debug

language: cpp

compiler:
  - clang
  - gcc


matrix:
  exclude:
    # OSX boost is compiled with Clang (skip gcc builds)
    - os: osx
      compiler: gcc
      env: CONFIG=Release
      
    - os: osx
      compiler: gcc
      env: CONFIG=Debug

before_script:
  - mkdir build
  - pushd $(pwd)
  - cd build

  # Build on Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake ../; fi
  
  # Build on OSX 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake ../; fi
  
  # Build & Install
  - make
  
  - popd

script:
  - pushd $(pwd)
  - cd build

  # Run C/C++ unittests
  - ctest --output-on-failure --force-new-ctest-process

  - popd
 
notifications:
  email:
    recipients:
      - thfabian@student.ethz.ch
    on_success: never
    on_failure: always

